export type Gender = "Male" | "Female" | "Agender" | "Genderfluid" | "Bigender" | "Genderqueer";

export interface IUser {
    id: number;
    first_name: string;
    last_name: string;
    email: string;
    gender: Gender;
    dob: string;
};

export const users: IUser[] = [
    {
        "id": 1,
        "first_name": "Dud",
        "last_name": "Lightbowne",
        "email": "dlightbowne0@alexa.com",
        "gender": "Male",
        "dob": "1/9/2022"
    }, {
        "id": 2,
        "first_name": "Sibel",
        "last_name": "Isgate",
        "email": "sisgate1@technorati.com",
        "gender": "Female",
        "dob": "2/23/2021"
    }, {
        "id": 3,
        "first_name": "Merrielle",
        "last_name": "O'Cosgra",
        "email": "mocosgra2@bravesites.com",
        "gender": "Female",
        "dob": "4/17/2021"
    }, {
        "id": 4,
        "first_name": "Frans",
        "last_name": "Forgie",
        "email": "fforgie3@fc2.com",
        "gender": "Male",
        "dob": "9/9/2021"
    }, {
        "id": 5,
        "first_name": "Helenka",
        "last_name": "Tomblett",
        "email": "htomblett4@google.co.uk",
        "gender": "Agender",
        "dob": "8/1/2021"
    }, {
        "id": 6,
        "first_name": "Toby",
        "last_name": "Pykerman",
        "email": "tpykerman5@hugedomains.com",
        "gender": "Female",
        "dob": "8/15/2021"
    }, {
        "id": 7,
        "first_name": "Denney",
        "last_name": "Popland",
        "email": "dpopland6@upenn.edu",
        "gender": "Male",
        "dob": "7/1/2021"
    }, {
        "id": 8,
        "first_name": "Dorella",
        "last_name": "Alyonov",
        "email": "dalyonov7@marketwatch.com",
        "gender": "Female",
        "dob": "4/16/2021"
    }, {
        "id": 9,
        "first_name": "Regan",
        "last_name": "Roony",
        "email": "rroony8@51.la",
        "gender": "Female",
        "dob": "9/8/2021"
    }, {
        "id": 10,
        "first_name": "Nelia",
        "last_name": "Bliben",
        "email": "nbliben9@geocities.com",
        "gender": "Female",
        "dob": "5/7/2021"
    }, {
        "id": 11,
        "first_name": "Arlen",
        "last_name": "Gadesby",
        "email": "agadesbya@facebook.com",
        "gender": "Female",
        "dob": "12/22/2021"
    }, {
        "id": 12,
        "first_name": "Jeromy",
        "last_name": "Blamphin",
        "email": "jblamphinb@auda.org.au",
        "gender": "Genderfluid",
        "dob": "12/13/2021"
    }, {
        "id": 13,
        "first_name": "Aloin",
        "last_name": "Brooks",
        "email": "abrooksc@economist.com",
        "gender": "Female",
        "dob": "12/7/2021"
    }, {
        "id": 14,
        "first_name": "Roarke",
        "last_name": "Romanin",
        "email": "rromanind@unicef.org",
        "gender": "Female",
        "dob": "5/14/2021"
    }, {
        "id": 15,
        "first_name": "Jerrine",
        "last_name": "Angrick",
        "email": "jangricke@dailymotion.com",
        "gender": "Male",
        "dob": "3/16/2021"
    }, {
        "id": 16,
        "first_name": "Jaymee",
        "last_name": "Gutridge",
        "email": "jgutridgef@seesaa.net",
        "gender": "Female",
        "dob": "10/25/2021"
    }, {
        "id": 17,
        "first_name": "Bax",
        "last_name": "Planks",
        "email": "bplanksg@opensource.org",
        "gender": "Female",
        "dob": "6/12/2021"
    }, {
        "id": 18,
        "first_name": "Sergei",
        "last_name": "Laterza",
        "email": "slaterzah@nps.gov",
        "gender": "Female",
        "dob": "11/6/2021"
    }, {
        "id": 19,
        "first_name": "Mickey",
        "last_name": "Edinburgh",
        "email": "medinburghi@rambler.ru",
        "gender": "Female",
        "dob": "8/13/2021"
    }, {
        "id": 20,
        "first_name": "Madelin",
        "last_name": "Dimitru",
        "email": "mdimitruj@deliciousdays.com",
        "gender": "Male",
        "dob": "12/24/2021"
    }, {
        "id": 21,
        "first_name": "Beale",
        "last_name": "McCullogh",
        "email": "bmcculloghk@sun.com",
        "gender": "Male",
        "dob": "5/4/2021"
    }, {
        "id": 22,
        "first_name": "Dyanna",
        "last_name": "Duke",
        "email": "ddukel@ftc.gov",
        "gender": "Female",
        "dob": "4/5/2021"
    }, {
        "id": 23,
        "first_name": "Laraine",
        "last_name": "Merali",
        "email": "lmeralim@java.com",
        "gender": "Male",
        "dob": "9/2/2021"
    }, {
        "id": 24,
        "first_name": "Jorry",
        "last_name": "Coram",
        "email": "jcoramn@independent.co.uk",
        "gender": "Male",
        "dob": "2/19/2021"
    }, {
        "id": 25,
        "first_name": "Nana",
        "last_name": "Thorley",
        "email": "nthorleyo@163.com",
        "gender": "Female",
        "dob": "5/27/2021"
    }, {
        "id": 26,
        "first_name": "Stevana",
        "last_name": "MacNeilly",
        "email": "smacneillyp@cornell.edu",
        "gender": "Agender",
        "dob": "2/14/2021"
    }, {
        "id": 27,
        "first_name": "Ambrosi",
        "last_name": "Alfonsetto",
        "email": "aalfonsettoq@mapquest.com",
        "gender": "Male",
        "dob": "2/14/2021"
    }, {
        "id": 28,
        "first_name": "Ax",
        "last_name": "Baurerich",
        "email": "abaurerichr@mozilla.org",
        "gender": "Female",
        "dob": "6/25/2021"
    }, {
        "id": 29,
        "first_name": "Benni",
        "last_name": "Batrim",
        "email": "bbatrims@1688.com",
        "gender": "Bigender",
        "dob": "11/23/2021"
    }, {
        "id": 30,
        "first_name": "Erasmus",
        "last_name": "Martugin",
        "email": "emartugint@themeforest.net",
        "gender": "Male",
        "dob": "2/20/2021"
    }, {
        "id": 31,
        "first_name": "Frederique",
        "last_name": "D'Antuoni",
        "email": "fdantuoniu@sogou.com",
        "gender": "Female",
        "dob": "2/21/2021"
    }, {
        "id": 32,
        "first_name": "Paddy",
        "last_name": "Coase",
        "email": "pcoasev@spiegel.de",
        "gender": "Female",
        "dob": "5/8/2021"
    }, {
        "id": 33,
        "first_name": "Rutherford",
        "last_name": "Mayo",
        "email": "rmayow@oakley.com",
        "gender": "Female",
        "dob": "5/11/2021"
    }, {
        "id": 34,
        "first_name": "Adriena",
        "last_name": "Phayre",
        "email": "aphayrex@wp.com",
        "gender": "Female",
        "dob": "6/12/2021"
    }, {
        "id": 35,
        "first_name": "Terese",
        "last_name": "Kleinstein",
        "email": "tkleinsteiny@oracle.com",
        "gender": "Agender",
        "dob": "1/28/2021"
    }, {
        "id": 36,
        "first_name": "Farley",
        "last_name": "Lanfear",
        "email": "flanfearz@purevolume.com",
        "gender": "Female",
        "dob": "8/19/2021"
    }, {
        "id": 37,
        "first_name": "Hetty",
        "last_name": "Torel",
        "email": "htorel10@clickbank.net",
        "gender": "Genderqueer",
        "dob": "9/8/2021"
    }, {
        "id": 38,
        "first_name": "Madlen",
        "last_name": "Dudbridge",
        "email": "mdudbridge11@hp.com",
        "gender": "Male",
        "dob": "8/25/2021"
    }, {
        "id": 39,
        "first_name": "Opalina",
        "last_name": "Bysaker",
        "email": "obysaker12@netlog.com",
        "gender": "Female",
        "dob": "1/18/2022"
    }, {
        "id": 40,
        "first_name": "Peyter",
        "last_name": "Andrzejowski",
        "email": "pandrzejowski13@nymag.com",
        "gender": "Female",
        "dob": "7/18/2021"
    }, {
        "id": 41,
        "first_name": "Tamarra",
        "last_name": "Allonby",
        "email": "tallonby14@trellian.com",
        "gender": "Male",
        "dob": "10/31/2021"
    }, {
        "id": 42,
        "first_name": "Giffy",
        "last_name": "Wade",
        "email": "gwade15@ucla.edu",
        "gender": "Male",
        "dob": "2/25/2021"
    }, {
        "id": 43,
        "first_name": "Allene",
        "last_name": "Ewenson",
        "email": "aewenson16@time.com",
        "gender": "Male",
        "dob": "8/15/2021"
    }, {
        "id": 44,
        "first_name": "Corene",
        "last_name": "Piscopello",
        "email": "cpiscopello17@reference.com",
        "gender": "Male",
        "dob": "11/6/2021"
    }, {
        "id": 45,
        "first_name": "Ellen",
        "last_name": "Dovidaitis",
        "email": "edovidaitis18@bizjournals.com",
        "gender": "Female",
        "dob": "9/2/2021"
    }, {
        "id": 46,
        "first_name": "Pyotr",
        "last_name": "Truelove",
        "email": "ptruelove19@mapquest.com",
        "gender": "Female",
        "dob": "12/5/2021"
    }, {
        "id": 47,
        "first_name": "Emile",
        "last_name": "Planque",
        "email": "eplanque1a@edublogs.org",
        "gender": "Female",
        "dob": "2/18/2021"
    }, {
        "id": 48,
        "first_name": "Hugibert",
        "last_name": "Wildes",
        "email": "hwildes1b@google.co.jp",
        "gender": "Female",
        "dob": "4/3/2021"
    }, {
        "id": 49,
        "first_name": "Joelie",
        "last_name": "Heggison",
        "email": "jheggison1c@github.io",
        "gender": "Male",
        "dob": "2/13/2021"
    }, {
        "id": 50,
        "first_name": "Rubina",
        "last_name": "Daventry",
        "email": "rdaventry1d@yahoo.co.jp",
        "gender": "Male",
        "dob": "11/25/2021"
    }
];
